### ISSUE TITLE
sometimes TypeError when creating media embed from queue embed

### ISSUE THREAD

**Issue by Whuppee** [Ethazeriel/goose#95]
was working. dismissed embeds, summoned a new queue embed, failed to create a media embed several times, dismissed that queue embed and summoned a new one, same failure. eventually worked again

consistently this error across all fails
```
[2022-10-03|23:54:45] - COMPONENT - Guild: Horse(888246961097048065), User: Whuppee#6367(160260330922967040), Source: queue show(1026749193764749333), Type: 2, ID: queue-showmedia
[2022-10-03|23:54:56] - ERROR - TypeError: fetch failed
    at Object.processResponse (/home/whup/discord-bot/server/node_modules/undici/lib/fetch/index.js:199:23)
    at /home/whup/discord-bot/server/node_modules/undici/lib/fetch/index.js:928:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[2022-10-03|23:55:47] - COMPONENT - Guild: Horse(888246961097048065), User: Whuppee#6367(160260330922967040), Source: queue show(1026749193764749333), Type: 2, ID: queue-showmedia
[2022-10-03|23:55:58] - ERROR - TypeError: fetch failed
    at Object.processResponse (/home/whup/discord-bot/server/node_modules/undici/lib/fetch/index.js:199:23)
    at /home/whup/discord-bot/server/node_modules/undici/lib/fetch/index.js:928:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[2022-10-03|23:56:19] - COMMAND - Guild: Horse(888246961097048065), User: Whuppee#6367(160260330922967040), Command: queue, ID: 1026749592852758569Subcommand: show, 
[2022-10-03|23:56:23] - COMPONENT - Guild: Horse(888246961097048065), User: Whuppee#6367(160260330922967040), Source: queue show(1026749593372864554), Type: 2, ID: queue-showmedia
[2022-10-03|23:56:33] - ERROR - TypeError: fetch failed
    at Object.processResponse (/home/whup/discord-bot/server/node_modules/undici/lib/fetch/index.js:199:23)
    at /home/whup/discord-bot/server/node_modules/undici/lib/fetch/index.js:928:38
    at node:internal/process/task_queues:140:7
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at AsyncResource.runMicrotask (node:internal/process/task_queues:137:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[2022-10-03|23:57:26] - COMPONENT - Guild: Horse(888246961097048065), User: Whuppee#6367(160260330922967040), Source: queue show(1026749593372864554), Type: 2, ID: queue-showmedia
```

**Comment by Ethazeriel** [comment]
closing this as a discord-internal error I generally can't do much about.
Ran into this today and after too much troubleshooting concluded that the issue was my https cert expired and didn't autorenew properly, so the embed thumbnail image was failing to load. way to fail gracefully, discord
